STEIN = "Jill Stein"
JOHNSON = "Gary Johnson"
MCMULLIN = "Evan McMullin"
TRUMP = "Donald Trump"
CLINTON = "Hillary Clinton"

THIRD_PARTY_CANDIDATES = [STEIN, JOHNSON, MCMULLIN]
CANDIDATES = [CLINTON, TRUMP, STEIN, JOHNSON, MCMULLIN]
